# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3193a07cb974c13df34a15aceaed70c39ae57de85815b5f5fb53287a2c5a9e6c76a1565cb264d60032e1ce7b69a88ad210cb96120c8501e116cc939cd7da28b

test:
  secret_key_base: da03951fae6bf38542797b05f579c7304160239f8de075371500bb9fb7d2ac4f3300c8b947ab36ce3613d3c952b764713f847bb4854a38e1f77ba3f7e41872f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
